services:
  mysql:
    container_name: 'product-api'
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=productdb'
      - 'MYSQL_PASSWORD=root'
      - 'MYSQL_ROOT_PASSWORD=root'
      - 'MYSQL_USER=adminuser'
    ports:
      - '3306:3306'